- hosts: localhost
  become: true
  tasks:
  - name: Update all packages to the latest version
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install etckeeper
    apt: name=etckeeper
  - name: Install vim
    apt: name=vim
  - name: Install docker ce requirements
    apt:
      name: "{{ item }}"
    with_items:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'software-properties-common'
  - name: Add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add docker registry
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  - name: install docker ce
    apt:
      name: docker-ce
      update_cache: yes
  - name: Ensure group "docker" exists
    group:
      name: docker
      state: present
  - name: Add the user 'jheylen' to docker group
    user:
      name: jheylen
      group: docker
